# Generated by Django 6.1.1 on 2026-10-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', '🍔 Food'), ('Transport', '🚗 Transport'), ('Bills', '🏠 Bills'), ('Shopping', '🛍️ Shopping'), ('Education', '📚 Education'), ('Entertainment', '🎬 Entertainment'), ('Health', '💊 Health'), ('Other', '📦 Other')], default='Other', max_length=30),
        ),
    ]
